# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Railway < Formula
  desc "Develop and deploy code with zero configuration"
  homepage "https://railway.app"
  version "1.7.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/railwayapp/cli/releases/download/v1.7.5/railway_1.7.5_darwin_amd64.tar.gz"
      sha256 "a014da1f2f65d477b82d1f4b658061ce5011c7a91469e93fbbaae6ec4ddb3fd4"

      def install
        bin.install "railway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/railwayapp/cli/releases/download/v1.7.5/railway_1.7.5_darwin_arm64.tar.gz"
      sha256 "2f1a53dce12dccb2f070fa6f6f414b9ec3fd9d9cba9c535e8800845155f110b5"

      def install
        bin.install "railway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/railwayapp/cli/releases/download/v1.7.5/railway_1.7.5_linux_arm64.tar.gz"
      sha256 "aa7c21281fc143f693c097d044c1f91211491099fff2c5e48e6f7e24749f42cc"

      def install
        bin.install "railway"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/railwayapp/cli/releases/download/v1.7.5/railway_1.7.5_linux_amd64.tar.gz"
      sha256 "462d1f4b9d2c525b5cd2f5e18ee8bb760dfafed2d69a105375c7ca231fb0b697"

      def install
        bin.install "railway"
      end
    end
  end
end
