# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Railway < Formula
  desc "Develop and deploy code with zero configuration"
  homepage "https://railway.app"
  version "0.2.42"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/railwayapp/cli/releases/download/v0.2.42/railway_0.2.42_darwin_amd64.tar.gz"
      sha256 "39e7e7dcdbffb9b0df4b0e063f18247b5af592cbc951754d78a37ebb267fb71c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/railwayapp/cli/releases/download/v0.2.42/railway_0.2.42_darwin_arm64.tar.gz"
      sha256 "d685318e3b37979bcff4accf57f1c664fcf83512d2c08107ceb8671b4fae1a48"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/railwayapp/cli/releases/download/v0.2.42/railway_0.2.42_linux_amd64.tar.gz"
      sha256 "ce9cee372185d266467e8f7a6ed6473d8b128fd6aac25789583c90ffda59b34d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/railwayapp/cli/releases/download/v0.2.42/railway_0.2.42_linux_arm64.tar.gz"
      sha256 "1bd131b171fd650d07a1ba79f397f5e340a03eeb1cb916a4fad0508712c4ffee"
    end
  end

  def install
    bin.install "railway"
  end
end
