# This file was generated by GoReleaser. DO NOT EDIT.
class Railway < Formula
  desc "Develop and deploy code with zero configuration"
  homepage "https://railway.app"
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/railwayapp/cli/releases/download/v0.0.7/railway_0.0.7_darwin_amd64.tar.gz"
    sha256 "8cf36fea3319e10dee3a544494e5100c7dda6c9c3116ef5548e477413c3ea3ac"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/railwayapp/cli/releases/download/v0.0.7/railway_0.0.7_linux_amd64.tar.gz"
      sha256 "21a7a3ec7d487ba7e218fa822cdd5ca802197c72d54980729d4966aeb56f0767"
    end
  end

  def install
    bin.install "railway"
  end
end
